name: Build and Push

on:
  push:
    tags:
      - v*

jobs:
  # Ensure that tests pass before publishing a new image.
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pvaneckw/modelmesh-controller
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
      - name: Run unit tests
        run: ./scripts/develop.sh make test
      # Depend on nightly builds for pushing for now.
      - name: Build runtime image
        run: make build
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION

          # Strip "v" prefix from tag name
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo $VERSION

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          docker push ${{ env.IMAGE_NAME }}:$VERSION
