name: Unit Test

on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!.github/**'
      - '!.tekton/**'
      - '!docs/**'
      - '!**.md'
      - '.github/workflows/unit-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run unit tests
        run: ./scripts/develop.sh make test
